name: Build

on:
  push:
    tags:
      - v*
  pull_request:
    paths: 
      - '**'

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            cibw_archs: "native"
          - os: ubuntu-latest
            cibw_archs: "aarch64"
          - os: windows-latest
            cibw_archs: "native"
          - os: macos-latest
            cibw_archs: "native arm64"

    steps:
      - name: Set up QEMU
        if: matrix.cibw_archs == 'aarch64'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.8.1
        env:
          CIBW_ARCHS: ${{ matrix.cibw_archs }}
          CIBW_SKIP: "pp*"
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: python {package}/test/debug.py && pytest {package}

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
  
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz
