name: Test sdist

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build sdist on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            cibw_archs: "native"

    steps:
      - uses: actions/checkout@v3

      - name: Build sdist
        run: pipx run build --sdist
      
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.1
        
        env:
          CIBW_ARCHS: ${{ matrix.cibw_archs }}
          CIBW_BUILD: "cp310-*"
          CIBW_SKIP: "*-musllinux_*"
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: python {package}/test/debug.py && pytest {package}
        with:
          package-dir: ${{ github.workspace }}/dist/frozendict-2.3.7.tar.gz
          
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
